name: Build and Release for JSR

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from deno.json
        uses: polyseam/get-version-key-from-json@v1.0.0
        id: get_deno_json
        with:
          path-to-json: "./deno.json"

      - name: Get the tag version without prefix
        id: get_version_from_ref
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - name: Compare Git Tag to deno.json version
        if: ${{ steps.get_deno_json.outputs.version != steps.get_version_from_ref.outputs.VERSION }}
        run: |
          echo "cconsole Version: ${{ steps.get_deno_json.outputs.version }} does not match Tag version: ${{ steps.get_version_from_ref.outputs.VERSION }}" && exit 1

      - name: Setup Deno CLI
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.2.2"

      - name: Checks
        run: deno task checks

      - name: Tests
        run: deno task test

      - run: deno publish
